[package]
name = "msi-psu-gui"
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-or-later"
[dependencies]
msi-psu = { path = "../.." }
anyhow = "1"
clap = { version = "4", features = ["derive", "env"] }
serde_json = "1"
chrono = "0.4"
slint = { version = "=1.17.1", default-features = false, features = ["accessibility", "backend-winit", "compat-1-2", "renderer-software", "std"] }
[build-dependencies]
slint-build = "=1.17.1"
